site_title = "MyArxiv"
limit_days = 7
cache_url = "https://zhuhu00.github.io/MyArxiv/cache.json"

[[sources]]
limit = 150
category = "cs.CV"
title = "Computer Vision and Pattern Recognition"

[[sources]]
limit = 150
category = "cs.AI"
title = "Artificial Intelligence"

[[sources]]
limit = 150
category = "cs.CG"
title = "Computational Geometry"

[[sources]]
limit = 150
category = "cs.GR"
title = "Graphics"

[[sources]]
limit = 150
category = "cs.LG"
title = "Machine Learning"

[[sources]]
limit = 150
category = "cs.MM"
title = "Multimedia"

[[sources]]
limit = 150
category = "cs.RO"
title = "Robotics"


[scripts]
highlight_title = "scripts/highlight_title.rhai"
highlight_author = "scripts/highlight_author.rhai"
highlight_conference = "scripts/highlight_conference.rhai"
